version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
       POSTGRES_USER: jbpm
       POSTGRES_PASSWORD: jbpm
       PGDATA: /data/postgres
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
# #       # copy the sql script to create tables
       - ./db/postgresql-jbpm-schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
#    volumes:
#      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  ibamoe-8-bc-persistence:
    container_name: bamoe
    image: ibamoe-8-bc-persistence:latest
    ports:
      - "8080:8080"
      - "8001:8001"
    volumes:
      - ~/.m2/repository:/opt/jboss/.m2/repository
      - ./bc_git:/home/jboss/.niogit
    depends_on:
      - db
  fakesmtp:
    container_name: fakesmtp
    image: hatamiarash7/fake-smtp:latest
    ports:
      - 25:25
    volumes:
      - ./fakemail:/output

volumes:
  postgres-data:
  pgadmin-data:



# version: '3.11'

# services:
#   postgresql:
#     image: postgres:13.2
#     container_name: pg-docker
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: jbpm
#       POSTGRES_PASSWORD: jbpm
#       PGDATA: /data/postgres
#     volumes:
#       - ./postgres-data:/var/lib/postgresql/data
# #       # copy the sql script to create tables
#       - ./db/postgresql-jbpm-schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
# #    command: postgres -c config_file=/etc/postgresql/postgresql.conf
#     restart: always



# version: '3.11'


# services:
#   postgres:
#     container_name: local_pgdb
#     image: postgres:13.2
#     environment:
#       POSTGRES_USER: jbpm
#       POSTGRES_PASSWORD: jbpm
#       PGDATA: /data/postgres
#     volumes:
#       - ./postgres-data:/var/lib/postgresql/data
#       # copy the sql script to create tables
#       - ./db/postgresql-jbpm-schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
#     ports:
#       - "5432:5432"


# volumes:
#   postgres-db:
#     driver: local

  # kie-server:
  #   container_name: kie-server
  #   image: jboss/jbpm-workbench-showcase:latest
  #   network_mode: host
  #   ports:
  #     - 8080:8080
  #     - 8001:8001
  #   depends_on:
  #     - postgres
  #   environment:
  #     # KIE Workbench environment variables
  #     # Neccessary to connect the KIE server to the KIE workbench
  #     - KIE_SERVER_ID=mykieserver
  #     - KIE_SERVER_DB_HOST=postgresdb
  #     - KIE_SERVER_DB_NAME=jbpm
  #     - KIE_SERVER_DB_USER=jbpm
  #     - KIE_SERVER_DB_PASSWORD=jbpm

