version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql.conf
    environment:
       POSTGRES_USER: jbpm
       POSTGRES_PASSWORD: jbpm
       PGDATA: /data/postgres
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
# #       # copy the sql script to create tables
       - ./db/postgresql-jbpm-schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
       - ./db/postgresql.conf:/etc/postgresql.conf
#    volumes:
#      - local_pgdata:/var/lib/postgresql/data

  ibamoe-8-bc-persistence:
    container_name: bamoe
    image: ibamoe-8-bc-persistence
    #To build your own version of the persistence image, run init-docker.sh in the docker
    # directory after downloading the files required for IBAMOE. Uncomment the next line and comment
    #out line 22
    #image: ibamoe-8-bc-persistence
    ports:
      - "8080:8080"
      - "8001:8001"
    volumes:
      - ~/.m2/repository:/opt/jboss/.m2/repository
      - ./bc_git:/home/jboss/.niogit
    depends_on:
      - db
  fakesmtp:
    container_name: fakesmtp
    image: hatamiarash7/fake-smtp:latest
    ports:
      - 25:25
    volumes:
      - ./fakemail:/output

  bamoe_canvas:
    container_name: bamoe_canvas
    image: quay.io/bamoe/canvas:9.0.0
    ports:
      - 9090:8080
    environment:      
       KIE_SANDBOX_REQUIRE_CUSTOM_COMMIT_MESSAGE: true
       KIE_SANDBOX_EXTENDED_SERVICES_URL: http://localhost:21345
       KIE_SANDBOX_GIT_CORS_PROXY_URL: http://localhost:7081
       KIE_SANDBOX_AUTH_PROVIDERS: > 
           [
            {
                "id": "github_dot_com",
                "domain": "github.com",
                "supportedGitRemoteDomains": [
                    "github.com",
                    "gist.github.com"
                ],
                "type": "github",
                "name": "GitHub",
                "enabled": true,
                "iconPath": "",
                "group": "git"
            },
            {
                "id": "gitlab_dot_com",
                "domain": "gitlab.com",
                "supportedGitRemoteDomains": [
                    "gitlab.com"
                ],
                "type": "gitlab",
                "name": "GitLab",
                "enabled": false,
                "iconPath": "images/gitlab-logo.svg",
                "group": "git"
            },
            {
                "id": "bitbucket_dot_com",
                "domain": "bitbucket.com",
                "supportedGitRemoteDomains": [
                    "bitbucket.com"
                ],
                "type": "bitbucket",
                "name": "Bitbucket",
                "enabled": false,
                "iconPath": "images/bitbucket-logo.svg",
                "group": "git"
            },
            {
                "enabled": true,
                "id": "openshift",
                "type": "openshift",
                "name": "OpenShift",
                "iconPath": "images/openshift-logo.svg",
                "group": "cloud"
            },
            {
                "enabled": false,
                "id": "kubernetes",
                "type": "openshift",
                "name": "Kubernetes",
                "iconPath": "images/kubernetes-logo.svg",
                "group": "cloud"
            }
            ,
            {
                "id": "GitHub_at_IBM",
                "domain": "github.ibm.com",
                "supportedGitRemoteDomains": [
                    "github.ibm.com",
                    "gist.github.ibm.com"
                ],
                "type": "github",
                "name": "GitHub Enterprise at IBM",
                "enabled": true,
                "group": "git"
            }
           ]

    depends_on:
      - kie_extended_services
      - cors
    

  kie_extended_services:
    container_name: bamoe_extended_services
    image: quay.io/bamoe/extended-services:9.0.0
    ports:
      - 21345:21345
    
  
  cors:
     image: quay.io/bamoe/git-cors-proxy:9.0.0
     container_name: cors
     ports:
      - 7081:8080
     



volumes:
  postgres-data:
  pgadmin-data: