version: "3.8"
services:
  kie_sandbox:
    container_name: ibm_canvas
    image: quay.io/bamoe/canvas:9.1.0-ibm-0001
    ports:
      - 9090:8080
    environment:      
       KIE_SANDBOX_REQUIRE_CUSTOM_COMMIT_MESSAGE: true
       KIE_SANDBOX_EXTENDED_SERVICES_URL: http://localhost:21345
       KIE_SANDBOX_CORS_PROXY_URL: http://localhost:7081
       KIE_SANDBOX_ACCELERATORS: >
         [
          {
            "name": "Quarkus",
            "iconUrl": "https://github.com/kiegroup/kie-sandbox-quarkus-accelerator/raw/0.0.0/quarkus-logo.png",
            "gitRepositoryUrl": "https://github.com/ibm/bamoe-canvas-quarkus-accelerator",
            "gitRepositoryGitRef": "9.1.0-quarkus-dmn",
            "dmnDestinationFolder": "src/main/resources/dmn",
            "bpmnDestinationFolder": "src/main/resources/bpmn",
            "otherFilesDestinationFolder": "src/main/resources/others"
          },
                    {
            "name": "Quarkus",
            "iconUrl": "https://github.com/kiegroup/kie-sandbox-quarkus-accelerator/raw/0.0.0/quarkus-logo.png",
            "gitRepositoryUrl": "https://github.com/ibm/bamoe-canvas-quarkus-accelerator",
            "gitRepositoryGitRef": "9.1.0-quarkus-full",
            "dmnDestinationFolder": "src/main/resources/dmn",
            "bpmnDestinationFolder": "src/main/resources/bpmn",
            "otherFilesDestinationFolder": "src/main/resources/others"
          }
         ]
  
       KIE_SANDBOX_AUTH_PROVIDERS: > 
           [
            {
                "id": "github_dot_com",
                "domain": "github.com",
                "supportedGitRemoteDomains": [
                    "github.com",
                    "gist.github.com"
                ],
                "type": "github",
                "name": "GitHub",
                "enabled": true,
                "iconPath": "",
                "group": "git"
            },
            {
                "id": "gitlab_dot_com",
                "domain": "gitlab.com",
                "supportedGitRemoteDomains": [
                    "gitlab.com"
                ],
                "type": "gitlab",
                "name": "GitLab",
                "enabled": true,
                "iconPath": "images/gitlab-logo.svg",
                "group": "git"
            },
            {
                "id": "bitbucket_dot_com",
                "domain": "bitbucket.com",
                "supportedGitRemoteDomains": [
                    "bitbucket.com"
                ],
                "type": "bitbucket",
                "name": "Bitbucket",
                "enabled": true,
                "iconPath": "images/bitbucket-logo.svg",
                "group": "git"
            },
            {
                "enabled": true,
                "id": "openshift",
                "type": "openshift",
                "name": "OpenShift",
                "iconPath": "images/openshift-logo.svg",
                "group": "cloud"
            },
            {
                "enabled": true,
                "id": "kubernetes",
                "type": "openshift",
                "name": "Kubernetes",
                "iconPath": "images/kubernetes-logo.svg",
                "group": "cloud"
            }
            ,
            {
                "id": "GitHub_at_IBM",
                "domain": "github.ibm.com",
                "supportedGitRemoteDomains": [
                    "github.ibm.com",
                    "gist.github.ibm.com"
                ],
                "type": "github",
                "name": "GitHub Enterprise",
                "enabled": true,
                "group": "git",
                "insecurelyDisableTlsCertificateValidation": true
            }
           ]

    depends_on:
      - extended_services
      - cors
    

  extended_services:
    container_name: extended_services
    image: quay.io/bamoe/extended-services:9.1.0-ibm-0001
    ports:
      - 21345:21345
    
  
  cors:
     image: quay.io/bamoe/cors-proxy:9.1.0-ibm-0001
     container_name: cors
     ports:
      - 7081:8080
  maven:
     image: quay.io/bamoe/maven-repository:9.1.0-ibm-0001
     container_name: maven-repository
     ports:
      - 31000:80
