version: "3.8"
services:
  kie_sandbox:
    container_name: kie_sandbox
    image: quay.io/kie-tools/kie-sandbox-image:latest
    ports:
      - 9090:8080
    environment:      
       KIE_SANDBOX_REQUIRE_CUSTOM_COMMIT_MESSAGE: true
       KIE_SANDBOX_EXTENDED_SERVICES_URL: http://localhost:21345
       KIE_SANDBOX_GIT_CORS_PROXY_URL: http://localhost:7081
       KIE_SANDBOX_AUTH_PROVIDERS: > 
           [
            {
                "id": "github_dot_com",
                "domain": "github.com",
                "supportedGitRemoteDomains": [
                    "github.com",
                    "gist.github.com"
                ],
                "type": "github",
                "name": "GitHub",
                "enabled": true,
                "iconPath": "",
                "group": "git"
            },
            {
                "id": "gitlab_dot_com",
                "domain": "gitlab.com",
                "supportedGitRemoteDomains": [
                    "gitlab.com"
                ],
                "type": "gitlab",
                "name": "GitLab",
                "enabled": false,
                "iconPath": "images/gitlab-logo.svg",
                "group": "git"
            },
            {
                "id": "bitbucket_dot_com",
                "domain": "bitbucket.com",
                "supportedGitRemoteDomains": [
                    "bitbucket.com"
                ],
                "type": "bitbucket",
                "name": "Bitbucket",
                "enabled": false,
                "iconPath": "images/bitbucket-logo.svg",
                "group": "git"
            },
            {
                "enabled": true,
                "id": "openshift",
                "type": "openshift",
                "name": "OpenShift",
                "iconPath": "images/openshift-logo.svg",
                "group": "cloud"
            },
            {
                "enabled": false,
                "id": "kubernetes",
                "type": "openshift",
                "name": "Kubernetes",
                "iconPath": "images/kubernetes-logo.svg",
                "group": "cloud"
            }
            ,
            {
                "id": "GitHub_at_IBM",
                "domain": "github.ibm.com",
                "supportedGitRemoteDomains": [
                    "github.ibm.com",
                    "gist.github.ibm.com"
                ],
                "type": "github",
                "name": "GitHub Enterprise at IBM",
                "enabled": true,
                "group": "git"
            }
           ]

    depends_on:
      - kie_extended_services
      - cors
    

  kie_extended_services:
    container_name: kie_extended_services
    image: quay.io/kie-tools/kie-sandbox-extended-services-image:latest
    ports:
      - 21345:21345
    
  
  cors:
     image: quay.io/kie-tools/git-cors-proxy-image
     container_name: cors
     ports:
      - 7081:8080
     
